feat: Change automatic line breaks to optional
vivliostyle/vfm pull request #64
Opened 2021-01-17 09:40 UTC by akabekobeko

#50 対応。

2021-01-17 09:46 UTC, akabekobeko commented
今回の PR から API やプロパティーなどにコード ドキュメントを付けるようにしました。コードが自己言及的に書かれていればコメントは不要という思想もありますが、最もコードに近い場所へ意図などを記述する場としてコメントはあったほうがよいと考えているため、今後はなるべく書く予定です。

IDE や VS Code など入力補完の効く環境下で API リファレンスとして機能することも狙っています。

2021-01-18 09:04 UTC, akabekobeko commented
すみません。CLI 対応が抜けてたので改めてコミットしました。もし CLI を試される場合は `sample.md` を以下の内容で作成して

```
テスト
テスト
```

VFM を `npm link` した後に `sample.md` の置かれた場所で

```
$ vfm sample.md
```

と

```
$ vfm sample.md --auto-line-breaks
```

を比較してください。既定値 `false` なのでオプション未指定はそのまま、指定すると改行位置に `<br>`　が挿入されます。

2021-01-18 09:07 UTC, akabekobeko commented
↑のコメントを書いて思ったのですが remark-breaks の処理は「変換」ではなく、改行位置へ `<br>` を挿入して元の改行は残るため「変換」以外で表現したほうがよいのかもしれません。

コード ドキュメントや CLI ヘルプでは "Convert" としましたが、なにかよい代替表現があればご指摘ください。またオプションもよりよい名前がありそうですね。

2021-01-18 17:20 UTC, spring-raining requested changes
PRありがとうございました。JSDocによるコメントなどありがたいです！

レビューコメント以外に一点、`autoLineBreaks` の有無による出力結果の変化についてテストがない状態なので、`tests/block/` 以下に追加していただけるとありがたいです。\
例えばGFMでは、改行1つによるautoLineBreaksはoffですが、行末に ` ` や `\` があると改行される仕様があります (https://gist.github.com/shaunlebron/746476e6e7a4d698b373 )。その点なども、testで確認できると良いかと思いました。

2021-01-18 17:20 UTC, spring-raining commented on src/revive-parse.ts
> +    results.splice(3, 0, breaks);
indexをマジックナンバーで指定して挿入する実装は `results` の変更への追従を忘れてしまう恐れがあるためおすすめできません。同等の実装は以下のコードでも可能です。

```ts
  const results = [
    (snip)
    ...(options.autoLineBreaks ? [breaks] : []),
    (snip)
  ];
```

2021-01-18 17:20 UTC, spring-raining commented on src/revive-parse.ts
> +export const reviveParse = (options: MarkdownOptions) => {
返値の型として `unified.PluggableList<unified.Settings>` を明示していただけますか？ その結果、`results` にある `as unified.PluggableList<unified.Settings>` を省略することが可能です。

2021-01-18 22:09 UTC, akabekobeko commented on src/revive-parse.ts
> +    results.splice(3, 0, breaks);
spread operator で条件分岐いけるのですね。マジックナンバーよりも好ましいのでこの方法に変更します。

2021-01-18 22:14 UTC, akabekobeko commented on src/revive-parse.ts
> +export const reviveParse = (options: MarkdownOptions) => {
元コードで直に配列を返す際の `as` を踏襲していましたが、関数化したなら確かに返り値の型で明示するほうが好ましいですね。そのように変更します。

2021-01-18 22:20 UTC, akabekobeko commented
`autoLineBreaks` のテストですが、追加しようとしたら `index.test.ts` に `handle hard line break` という名で存在していたためやめました。ただしこれは「常時 `remark-breaks` が実行されること」を想定して `index.test.ts` に定義されているようですので、

> `tests/block/` 以下に追加していただけるとありがたいです。

で対応します。

2021-01-18 23:56 UTC, akabekobeko commented
指摘のあった箇所を修正しました。`reviveParse` は返り値における型の明示ついでに処理が `return` のみとなったため、略記にしてあります。

2021-01-18 23:57 UTC, akabekobeko commented
現時点の対応でよろしければ merge しますので、お手すきの時に再レビューをお願いします。

2021-01-19 16:32 UTC, MurakamiShinyu commented
--auto-line-breaks という名前ですが、長い行を自動で改行を入れるという意味かと誤解されるかもしれません。

Pandocはオプションで改行の扱いを変えることができるので、それに倣うのがよいと思います。

https://pandoc.org/MANUAL.html#extension-hard_line_breaks

> #### Extension: `hard_line_breaks`
>
> Causes all newlines within a paragraph to be interpreted as hard line breaks instead of spaces.
>
> #### Extension: `ignore_line_breaks`
>
> Causes newlines within a paragraph to be ignored, rather than being treated as spaces or as hard line breaks. This option is intended for use with East Asian languages where spaces are not used between words, but text is divided into lines for readability.
>
> #### Extension: `east_asian_line_breaks`
>
> Causes newlines within a paragraph to be ignored, rather than being treated as spaces or as hard line breaks, when they occur between two East Asian wide characters. This is a better choice than `ignore_line_breaks` for texts that include a mix of East Asian wide characters and other characters.

テスト:
```
$ pandoc --from=markdown+hard_line_breaks
```

```md
The quick brown fox
jumps over the lazy dog.
```
↓
```html
<p>The quick brown fox<br />
jumps over the lazy dog.</p>
```

ということで、`--auto-line-breaks` を `--hard-line-breaks` に変更することを提案します。

2021-01-19 22:27 UTC, akabekobeko commented
> ということで、`--auto-line-breaks` を `--hard-line-breaks` に（`autoLineBreaks` を `hardLineBreaks` に）変更することを提案します。

いい案ですね。対応します。

2021-01-19 22:52 UTC, akabekobeko commented
村上さんのオプション名案を反映しました

2021-01-20 11:02 UTC, akabekobeko commented
@spring-raining @MurakamiShinyu 
現時点のコードでよろしければ、その旨をお知らせください。merge したいと思います。

2021-01-20 13:43 UTC, spring-raining commented on README.md
> +    - [`autoLineBreaks` (default: `false`)](#autoLineBreaks-default-false)
```suggestion
    - [`hardLineBreaks` (default: `false`)](#hardLineBreaks-default-false)
```

2021-01-20 13:43 UTC, spring-raining commented on README.md
> +#### `autoLineBreaks` (default: `false`)
```suggestion
#### `hardLineBreaks` (default: `false`)
```

2021-01-20 13:43 UTC, spring-raining commented on README.md
> +  { autoLineBreaks: true },
```suggestion
  { hardLineBreaks: true },
```

2021-01-20 14:17 UTC, akabekobeko commented
@spring-raining ありがとうございます。指摘のあった README の変更漏れを修正しました。

2021-01-20 14:22 UTC, spring-raining approved these changes
良さそうです！

2021-01-20 14:27 UTC, merged

2021-01-20 14:27 UTC, akabekobeko commented
@spring-raining @MurakamiShinyu レビューありがとうございました！

2021-01-20 15:04 UTC, MurakamiShinyu approved these changes
LGTM